### ISSUE TITLE
Evol - endpoint not defined

### ISSUE THREAD

**Issue by MatthieuPresse** [Ouest-France/platform#19]
Le bp algolia n' a pas de endpoint dans sa block config - et c'est normal / voulu.
Par contre le validator cli nous envoie 
`logLevel: "ERROR",
message: "object has missing required properties (["endpoint"])",
},`

Il faudrait prévoir ce cas la pour qu'on puisse ajouter la validation du config lors d'une étape de test de la cdp du bp algolia

**Comment by FGRibreau** [comment]
Fixed :tada:
